# Generated by Django 5.2.1 on 2025-05-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaBCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('valor', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
